###
POST https://3000-arunk555-bookstore-k2j5f3ukxtt.ws-us77.gitpod.io/v1.0/admin/register HTTP/1.1
Content-Type: application/json

{
    "name" : "ArunK",
    "email" : "aruncse14@gmail.com",
    "password" : "Welcome@123"
}

###
POST  https://3000-arunk555-bookstore-k2j5f3ukxtt.ws-us77.gitpod.io/v1.0/admin/login
Content-Type: application/json


{
    "email" : "aruncse14@gmail.com",
    "password" : "Welcome@123"
}

###
POST https://3000-arunk555-bookstore-k2j5f3ukxtt.ws-us77.gitpod.io/v1.0/admin/me
Content-Type: application/json

Authorization: Bearer 

Authorization: Bearer 
